ZaferTurizm.WebApp/Controllers/VehicleDefinitionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ZaferTurizm.Business.Services.VehicleDefinitionManagers;
using ZaferTurizm.Business.Services.VehicleMakeManagers;
using ZaferTurizm.Business.Services.VehicleModelManagers;
using ZaferTurizm.DTOs.VehicleDefinitionAllDtos;

namespace ZaferTurizm.WebApp.Controllers
{
    public class VehicleDefinitionController : Controller
    {
        private readonly IVehicleDefinitionService _vehicleDefinitonService;
        private readonly IVehicleModelService _vehicleModelService;
        private readonly IVehicleMakeService _vehicleMakeService;
        public VehicleDefinitionController(
            IVehicleDefinitionService vehicleDefinitonService, 
            IVehicleModelService vehicleModelService, 
            IVehicleMakeService vehicleMakeService) 
        {
            _vehicleDefinitonService = vehicleDefinitonService;
            _vehicleModelService = vehicleModelService;
            _vehicleMakeService = vehicleMakeService;
            
        }

        


        public IActionResult Index()
        {
            return View(_vehicleDefinitonService.GetSummaries());
        }
        public IActionResult Create() 
        {
            var makeList = _vehicleMakeService.GetAll();
            ViewBag.MakeList = new SelectList(makeList,"Id","Name");
            var modelList = _vehicleModelService.GetAll();
            ViewBag.ModelList = new SelectList(modelList, "Id", "Name");
            
            return View();
        }
       
        [HttpPost]
        public IActionResult Create(VehicleDefinitionDto vdo)
        {
            if (vdo == null)
            {
                return Json("Ekleme işlemi başarısız,model boş");
            }
            var result = _vehicleDefinitonService.Create(vdo);

            return Json(result);
            
            

            
        }
        public IActionResult Edit(int id)
        {
            var vd = _vehicleDefinitonService.GetById(id);
            if (vd==null)
            {
                return NotFound();
            }

            var makeList = _vehicleMakeService.GetAll();
            ViewBag.MakeList = new SelectList(
                makeList, 
                "Id", 
                "Name",
                vd.VehicleMakeId);
            var modelList = _vehicleModelService.GetByMakeId(vd.VehicleMakeId);
            ViewBag.ModelList = new SelectList(
                modelList,
                "Id",
                "Name");
                
                
           

            return View(vd);
        }
        [HttpPost]
        public IActionResult Edit(VehicleDefinitionDto vdo)
        {
            if (vdo == null) return Ok();
            var result = _vehicleDefinitonService.Update(vdo);
            if(result.IsSuccess)
            {
                return RedirectToAction("Index");
            }
            else
            {
                var makeList = _vehicleMakeService.GetAll();
                ViewBag.MakeList = new SelectList(
                    makeList,
                    "Id",
                    "Name",
                    vdo.VehicleMakeId);


                return View(vdo);
            }
        }
        public IActionResult Delete(int id)
        {
            if(id == 0)  return Json("Bu boş la"); 
            var result = _vehicleDefinitonService.Delete(id);
            return Json(result.Message);
        }
    }
}

ZaferTurizm.WebApp/Controllers/VehicleModelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;
using System.Reflection.Metadata.Ecma335;
using ZaferTurizm.Business.Services.VehicleMakeManagers;
using ZaferTurizm.Business.Services.VehicleModelManagers;
using ZaferTurizm.Domain;
using ZaferTurizm.DTOs.VehicleModelAllDtos;

namespace ZaferTurizm.WebApp.Controllers
{
    public class VehicleModelController : Controller
    {
        private readonly IVehicleModelService _vehicleModelService;
        private readonly IVehicleMakeService _vehicleMakeService;
        private readonly IToastNotification _toastNotification;

        public VehicleModelController(
            IVehicleModelService vehicleModelService,
            IVehicleMakeService vehicleMakeService,
            IToastNotification toastNotification)
        {
            _vehicleModelService = vehicleModelService;
            _vehicleMakeService = vehicleMakeService;
            _toastNotification = toastNotification;
        }

        public IActionResult Create()

        {
            FillVehicleMakeList();

            return View();
        }
        [HttpPost]
        public IActionResult Create(VehicleModelDto vmo)
        {
            if(vmo.Name==null)
            {
                
                _toastNotification.AddWarningToastMessage("Model ismi boş,tekrar deneyiniz");
                FillVehicleMakeList();

                return View();
            }
           var result = _vehicleModelService.Create(vmo);
            if (result.IsSuccess)
            {
                _toastNotification.AddSuccessToastMessage("Model başarıyla eklendi.");
                return RedirectToAction("Index");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Ekleme İşlemi Başarısız");
                FillVehicleMakeList();
                return View();
            }
        }
        private void FillVehicleMakeList()
        {
            var vehicleMakes = _vehicleMakeService.GetAll();
            
            ViewBag.VehicleMakeSelectList = new SelectList(vehicleMakes, "Id", "Name");
        }
        public IActionResult Index()
        {
            
            return View(_vehicleModelService.GetSummaries());
        }
        [HttpPost]
        public IActionResult Delete(int id) 
        {
            var result = _vehicleModelService.Delete(id);
           
            return Json(result.Message);
        }
        public IActionResult Edit(int id)
        {
            FillVehicleMakeList();
            var vehModel = _vehicleModelService.GetById(id);
          
            return View(vehModel);
        }

        [HttpPost]
        public IActionResult Edit(VehicleModelDto vmo)
        {
            var result = _vehicleModelService.Update(vmo);
            if (result.IsSuccess)
            {
                _toastNotification.AddSuccessToastMessage("Model Başarıyla Güncellendi.");
                return RedirectToAction(nameof(Index));
            }

            else 
            {

                FillVehicleMakeList();
                return View(vmo);

            }

            
            
        }
        public IActionResult GetVehicleModelsById(int vehicleMakeId)
        {
            var modelsByVehiclesId = _vehicleModelService.GetByMakeId(vehicleMakeId);
            return Json(modelsByVehiclesId);
        }
    }
}
            
            

ZaferTurizm.WebApp/Views/VehicleDefinition/Create.cshtml
@model VehicleDefinitionDto

<h1>Yeni Araç Modeli</h1>
<div class="row">
    <div class="col-12 col-sm-8 col-md-6">
        <form method ="post" asp-controller="VehicleDefinition" asp-action="Create">
           <div class="form-group">
                <div>
                    <label class="form-label">Marka Adı</label>
                    <select asp-items="(SelectList)ViewBag.MakeList" id="vehicle_makes" value="" class="form-select w-100">
                        <option value="">-- Seçiniz --</option>
                    </select>
                    @*@Html.TextBoxFor(m=>m.Name,new {@class="form-control"})*@
                </div> @*asp-itemsa SelectListitem göndermen gerekiyor*@
                <div class="mt-2">
                    <label class="form-label">Model Adı</label>
                    <select class="form-select w-100" asp-for=VehicleModelId></select>
                    @*@Html.DropDownListFor(m=>m.Id,(SelectList)ViewBag.VehicleMakeList,new {@class="form-control"}) @*For yazınca modelden seçebiliyoruz modelden*@
                </div>
                <div>
                    <label class="form-label">Yıl</label>
                    <input class="form-control w-100" asp-for="Year" />
                    
                </div>
                <div>
                    <label class="form-label">Yolcu Kapasitesi</label>
                    <input class="form-control w-100" asp-for="SeatCount" />

                </div>
                <div class="form-group">
                    <label class="form-label">Tuvalet</label>
                    <input  type="checkbox" asp-for="HasToilet" class="form-check" />

                </div>
                <div class="form-group">
                    <label class="form-label">WiFi</label>
                    <input type="checkbox" asp-for="HasWifi" class="form-check" />
                </div>

                <div class="mt-2">
                    <button id="create-button" type="submit" class="btn btn-success">
                        Kaydet
                    </button>
                </div>

           </div>
        </form>
    </div>

</div>
<!--
    AJAX
    Asynchronous Javascript And XML
    Asynchronous Javascript And XML
-->
@section Scripts
    {
    <script>
        //let vehicleMakesSelect=document.getElementById('vehicle_makes');

        let vehicleMakesSelect = document.querySelector('#vehicle_makes');
        vehicleMakesSelect.addEventListener('change', function () {

            // Elementin kendisi ==>this

            

            $.ajax({
                    url: `/VehicleModel/GetVehicleModelsById?vehicleMakeId=${this.value}`,
                    method: 'get',
                    success: function (vehicleModels) {
                    
                    var vehicleModelsSelect =document.querySelector('#VehicleModelId');
                    vehicleModelsSelect.innerHTML=null;
                    for(let vehicleModel of vehicleModels) {

                        let optionElement = document.createElement('option');
                        optionElement.value=vehicleModel.id;
                        optionElement.innerText=vehicleModel.name;
                        vehicleModelsSelect.appendChild(optionElement);

                    }

                }
                

            });
        })
    </script>
    <script>
        $(function() {
            $('form').submit(function(event) {
                event.preventDefault(); // Formun otomatik olarak submit olmasını engeller

                // AJAX isteğini gönderme
                $.ajax({
                    url: $(this).attr('action'), // Formun action değerini kullanır
                    type: $(this).attr('method'), // Formun method değerini kullanır
                    data: $(this).serialize(), // Form verilerini serialize eder
                    success: function(response) {
                        // AJAX isteği başarılı olduğunda çalışacak kodlar
                        // Mesajı alert olarak gösterme
                        // İstenilen diğer işlemleri gerçekleştirme
                        let confirmed = confirm(`${response.message}\n Yeni bir ekleme yapmak istiyor musunuz`);
                        if(confirmed) 
                        {

                            window.location.href='/VehicleDefinition/Create'
                        }
                        else {
                            window.location.href = '/VehicleDefinition/Index'
                        }
                        
                    },
                    error: function(error) {
                        // AJAX isteği başarısız olduğunda çalışacak kodlar
                    }
                });
            });
        });
    </script>
    

    
       
   

    @*<script>

        //Literal Objects
        let player = {
            firstName: 'Tsubasa',
            lastName: 'Ozora',

        }
    </script>*@
}

ZaferTurizm.WebApp/Views/VehicleDefinition/Edit.cshtml
@model VehicleDefinitionDto

<h1>Araç Tanımı Güncelleme</h1>
<div class="row">
    <div class="col-12 col-sm-8 col-md-6">
        <form method="post" asp-controller="VehicleDefinition" asp-action="Edit">
            
            <input type="hidden" asp-for="Id" />
            <div>
                <label class="form-label">Marka Adı</label>
                <select asp-for="VehicleMakeId" id="vehicle_makes" asp-items="(SelectList)ViewBag.MakeList" value="" class="form-select w-100"></select>
                @*@Html.TextBoxFor(m=>m.Name,new {@class="form-control"})*@
            </div> @*asp-itemsa SelectListitem göndermen gerekiyor*@
            <div class="mt-2">
                <label class="form-label">Model Adı</label>
                <select asp-for="VehicleModelId" class="form-select w-100" asp-items="(SelectList)ViewBag.ModelList" asp-for=VehicleModelId></select>
                @*@Html.DropDownListFor(m=>m.Id,(SelectList)ViewBag.VehicleMakeList,new {@class="form-control"}) @*For yazınca modelden seçebiliyoruz modelden*@
            </div>
            <div>
                <label class="form-label">Yıl</label>
                <input class="form-control w-100" asp-for="Year" />

            </div>
            <div>
                <label class="form-label">Yolcu Kapasitesi</label>
                <input class="form-control w-100" asp-for="SeatCount" />

            </div>
            <div class="form-group">
                <label class="form-label">Tuvalet</label>
                <input type="checkbox" asp-for="HasToilet" class="form-check" />

            </div>
            <div class="form-group">
                <label class="form-label">WiFi</label>
                <input type="checkbox" asp-for="HasWifi" class="form-check" />
            </div>
            <div class="mt-2">
                <button type="submit" class="btn btn-success">
                    Kaydet
                </button>
            </div>

        </form>
    </div>

</div>

@section Scripts
    {
    <script>
        //let vehicleMakesSelect=document.getElementById('vehicle_makes');

        let vehicleMakesSelect = document.querySelector('#vehicle_makes');
        vehicleMakesSelect.addEventListener('change', function () {

            // Elementin kendisi ==>this

            console.log(this.value)

            $.ajax({
                url: `/VehicleModel/GetVehicleModelsById?vehicleMakeId=${this.value}`,
                method: 'get',
                success: function (vehicleModels) {

                    var vehicleModelsSelect = document.querySelector('#VehicleModelId');
                    vehicleModelsSelect.innerHTML = null;
                    for (let vehicleModel of vehicleModels) {

                        let optionElement = document.createElement('option');
                        optionElement.value = vehicleModel.id;
                        optionElement.innerText = vehicleModel.name;
                        vehicleModelsSelect.appendChild(optionElement);

                    }

                }


            });
        })
    </script>

    @*<script>

        //Literal Objects
        let player = {
            firstName: 'Tsubasa',
            lastName: 'Ozora',

        }
    </script>*@
}

ZaferTurizm.WebApp/Views/VehicleDefinition/Index.cshtml
@model IEnumerable<VehicleDefinitonSummary>

<h1>Araçlar</h1>

<div class="row">
    <div class="col-12">
        <div class="text-end mb-2">
            <a asp-controller="VehicleDefinition" asp-action="Create" class="btn btn-outline-primary btn-sm float-end mb-2">Yeni Ekle</a>
        </div>
        <table class="table table-striped table-bordered" id="myTable">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Marka Adı</th>
                    <th>Model Adı</th>
                    <th>Yılı</th>
                    <th>Koltuk Numarası</th>
                    <th>Tuvalet</th>
                    <th>Wifi</th>
                    <th>İşlemler</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.VehicleMakeName</td>
                        <td>@item.VehicleModelName</td>
                        <td>@item.Year</td>
                        <td>@item.SeatCount</td>
                        <td>@item.HasToiletString</td>
                        <td>@item.HasWifiString</td>
                        <td>
                            <div class="btn-group">
                                @*Bu yola Tag Helpers denir.. daha yaygın*@
                                <button class="btn btn-danger bbara" data-vehicle-def-id="@item.Id">Sil</button> @*İd benim parametre adım*@

                                @*@Html.ActionLink("Sil","Delete","VehicleModel", new {id=item.Id}) --> Bu yol html helpers *@
                                <a class="btn btn-warning d-inline-block ms-2" asp-controller="VehicleDefinition" asp-action="Edit" asp-route-id="@item.Id">Güncelle</a>


                            </div>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
        
    </div>
</div>

@section Scripts{
    <script>
           let buttons = document.getElementsByClassName('bbara');
           for(let i=0;i<buttons.length;i++){
               var delButton = buttons[i];
               delButton.addEventListener('click', function(e){
                   e.preventDefault();

                   $.ajax({
                       url:`/VehicleDefinition/Delete?id=${this.dataset.vehicleDefId}`,
                       method:'get',
                       success: function(event) {
                           alert(event);
                           window.location.reload();
                       }
                   })
               })

           }
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
}