ZaferTurizm.WebApp/Controllers/PassengerController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata;
using System.Xml.Linq;
using ZaferTurizm.Business.Services.BusTripManagers;
using ZaferTurizm.Business.Services.PassengerManagers;
using ZaferTurizm.Business.Services.TicketManagers;
using ZaferTurizm.DTOs.TicketAllDtos;
using Document = iTextSharp.text.Document;

namespace ZaferTurizm.WebApp.Controllers
{
    public class PassengerController : Controller
    {
        private readonly IBusTripService _bustripService;
        private readonly IPassengerService _passengerService;
        private readonly ITicketService _ticketService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PassengerController(IBusTripService bustripService,
                                   IPassengerService passengerService, 
                                    ITicketService ticketService,
                                    IWebHostEnvironment webHostEnvironment)
        {
            _bustripService = bustripService;
            _passengerService = passengerService;
            _ticketService = ticketService;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var ticketsAll = _ticketService.GetSummaries();
           
            return View(ticketsAll);
        }
        public IActionResult Details(int id)
        {
            var summary = _ticketService.GetSummaryById(id);
            return View(summary);
        }
        public ActionResult ExportToPDF(int id)
        {
            var model = _ticketService.GetSummaryById(id);
            
           
            MemoryStream memoryStream = new MemoryStream();

           
            Document document = new Document();

           
            PdfWriter writer = PdfWriter.GetInstance(document, memoryStream);

            
            document.Open();

           
            Font titleFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 18);

           
            Paragraph title = new Paragraph($"{model.PassengerFName} {model.PassengerLName} Bilet Bilgileri", titleFont);
            title.Alignment = Element.ALIGN_CENTER;
            title.SpacingAfter = 10f;
            document.Add(title);

            
            PdfPTable table = new PdfPTable(2);
            table.WidthPercentage = 100;
            table.SetWidths(new float[] { 1f, 2f });

            string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "OtobusResimleri", "Zafer-Partisi.png");
            Image image = Image.GetInstance(imagePath);
            image.ScaleToFit(150f, 150f);
            image.Alignment = Element.ALIGN_CENTER;
            document.Add(image);


            // Tabloyu doldur
            table.AddCell("Sefer Tarihi:");
            table.AddCell(model.Date.ToString());

            table.AddCell("Tc Kimlik Numarası:");
            table.AddCell(model.PassengerIdentityNumber);
            table.AddCell("Ad - Soyad:");
            table.AddCell($"{model.PassengerFName} {model.PassengerLName}");

            table.AddCell("Yolcu Yasi:");
            table.AddCell(model.Age.ToString());

            table.AddCell("İletisim Bilgileri:");
            table.AddCell(model.PhoneNumber);

            table.AddCell("Koltuk Numarasi:");
            table.AddCell(model.SeatNumber.ToString());

            document.Add(table);

            // Resmi ekle
           

            // Diğer bilgileri ekle
            Paragraph busTripName = new Paragraph(model.BusTripName, FontFactory.GetFont(FontFactory.COURIER_BOLD, 20));
            busTripName.Alignment = Element.ALIGN_CENTER;
            document.Add(busTripName);

            Paragraph route = new Paragraph(model.Route);
            route.Alignment = Element.ALIGN_CENTER;
            document.Add(route);

            Paragraph paidAmount = new Paragraph($"Bilet Fiyatı: {model.PaidAmount}", FontFactory.GetFont(FontFactory.HELVETICA, 14));
            paidAmount.Alignment = Element.ALIGN_CENTER;
            document.Add(paidAmount);

            // PDF belgesini kapatın
            document.Close();

            // Bellek akışını baytlara dönüştürerek PDF dosyasını alın
            byte[] bytes = memoryStream.ToArray();

            // PDF dosyasını kullanıcıya indirme olarak sunmak için FileResult döndürün
            return File(bytes, "application/pdf", $"{model.PassengerFName}.pdf");
        }
    }

}
    

ZaferTurizm.WebApp/Controllers/VehicleModelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;
using System.Reflection.Metadata.Ecma335;
using ZaferTurizm.Business.Services.VehicleMakeManagers;
using ZaferTurizm.Business.Services.VehicleModelManagers;
using ZaferTurizm.Domain;
using ZaferTurizm.DTOs.VehicleModelAllDtos;

namespace ZaferTurizm.WebApp.Controllers
{
    public class VehicleModelController : Controller
    {
        private readonly IVehicleModelService _vehicleModelService;
        private readonly IVehicleMakeService _vehicleMakeService;
        private readonly IToastNotification _toastNotification;

        public VehicleModelController(
            IVehicleModelService vehicleModelService,
            IVehicleMakeService vehicleMakeService,
            IToastNotification toastNotification)
        {
            _vehicleModelService = vehicleModelService;
            _vehicleMakeService = vehicleMakeService;
            _toastNotification = toastNotification;
        }

        public IActionResult Create()

        {
            FillVehicleMakeList();

            return View();
        }
        [HttpPost]
        public IActionResult Create(VehicleModelDto vmo)
        {
            if(vmo.Name==null)
            {
                
                _toastNotification.AddWarningToastMessage("Model ismi boş,tekrar deneyiniz");
                FillVehicleMakeList();

                return View();
            }
           var result = _vehicleModelService.Create(vmo);
            if (result.IsSuccess)
            {
                _toastNotification.AddSuccessToastMessage("Model başarıyla eklendi.");
                return RedirectToAction("Index");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Ekleme İşlemi Başarısız");
                FillVehicleMakeList();
                return View();
            }
        }
        private void FillVehicleMakeList()
        {
            var vehicleMakes = _vehicleMakeService.GetAll();
            
            ViewBag.VehicleMakeSelectList = new SelectList(vehicleMakes, "Id", "Name");
        }
        public IActionResult Index()
        {
            
            return View(_vehicleModelService.GetSummaries());
        }
        [HttpPost]
        public IActionResult Delete(int id) 
        {
            var result = _vehicleModelService.Delete(id);
           
            return Json(result.Message);
        }
        public IActionResult Edit(int id)
        {
            FillVehicleMakeList();
            var vehModel = _vehicleModelService.GetById(id);
          
            return View(vehModel);
        }

        [HttpPost]
        public IActionResult Edit(VehicleModelDto vmo)
        {
            var result = _vehicleModelService.Update(vmo);
            if (result.IsSuccess)
            {
                _toastNotification.AddSuccessToastMessage("Model Başarıyla Güncellendi.");
                return RedirectToAction(nameof(Index));
            }

            else 
            {

                FillVehicleMakeList();
                return View(vmo);

            }

            
            
        }
        public IActionResult GetVehicleModelsById(int vehicleMakeId)
        {
            var modelsByVehiclesId = _vehicleModelService.GetByMakeId(vehicleMakeId);
            return Json(modelsByVehiclesId);
        }
    }
}
            
            

ZaferTurizm.WebApp/Views/Passenger/Details.cshtml
@model TicketSummary

<h1>@Model.PassengerFName  @Model.PassengerLName  Bilet Bilgileri</h1>

<div class="row">
    <div class="col-12">
        <div class="text-end mb-2">
            <a asp-controller="Passenger" asp-action="ExportToPdf" asp-route-id="@Model.Id" class="btn btn-success">Bileti Yazdır</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12 border border-dark rounded-2">
        <div class="row ">
            <div class="col-4 pt-4 align-items-center justify-content-center">
                <div class="row">
                    <div class="col-12">Sefer Tarihi : @Model.Date</div>
                </div>
                <div class="row border-top">
                    <div class="col-6">Tc Kimlik Numarası : </div>
                    <div class="col-6">@Model.PassengerIdentityNumber</div>
                </div>
                <div class="row border-top">
                    <div class="col-6">Ad - Soyad</div>
                    <div class="col-6">@Model.PassengerFName @Model.PassengerLName</div>
                </div>
                <div class="row border-top">
                    <div class="col-6">Yolcu Yaşı</div>
                    <div class="col-6">@Model.Age</div>
                </div>
                <div class="row border-top">

                    <div class="col-6">İletişim Bilgileri</div>
                    <div class="col-6">@Model.PhoneNumber</div>

                </div>
                <div class="row border-top">
                    <div class="col-6">Koltuk Numarası :</div>
                    <div class="col-6">@Model.SeatNumber</div>

                </div>
            </div>
            <div class="col-4">
                <img src="/OtobusResimleri/Zafer-Partisi.png" class="img-fluid" />
            </div>
            <div class="col-4">
                <div class="row">
                    <h2>@Model.BusTripName</h2>
                    <div class="h3">@Model.Route</div>
                </div>
                <div class="row pt-3 border-top text-center h4">
                    <div class="col-6">Bilet Fiyatı :</div>
                    <div class="col-6">@Model.PaidAmount</div>
                </div>
            </div>
        </div>
    </div>
</div>

ZaferTurizm.WebApp/Views/Passenger/Index.cshtml
@model IEnumerable<TicketSummary>

<h1>Yolcular</h1>

<div class="row">
    <div class="col-12">
        <div class="text-end mb-2">
            <a asp-controller="Home" asp-action="Index" class="btn btn-outline-primary btn-sm float-end mb-2">Yeni Bilet Al</a>
        </div>
        <table class="table table-striped table-bordered" id="myTable">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Yolcu Bilgileri</th>
                    <th>Sefer Bilgileri</th>
                    
                    <th>İşlemler</th>
                    
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.PassengerInfos</td>
                        <td>@item.BusTripName</td>
                        
                        
                        <td>
                            <div class="btn-group">
                                @*Bu yola Tag Helpers denir.. daha yaygın*@
                                

                                @*@Html.ActionLink("Sil","Delete","VehicleModel", new {id=item.Id}) --> Bu yol html helpers *@
                                <a class="btn btn-warning d-inline-block ms-2" asp-controller="Passenger" asp-action="Details" asp-route-id="@item.Id">Detaylar</a>


                            </div>

                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
}